services:
  streamx-bot:
    container_name: streamXBot
    build:
      context: .
      dockerfile: Dockerfile

    command: ["bash", "/app/start.sh"]

    ports:
      - "8000:8000"  
      
    restart: on-failure