BOT_TOKEN = ""
API_ID = 00000000
API_HASH = ""
MONGO_URI = ""
DATABASE_NAME = "Stream"
OWNER_ID = 100000000
SUDO_USERS = [100000000]
SECRET_KEY="SHAXXXXXXXXXXXXXXXXXXX"

# DEBUG
DEBUG = False

# API
CORS_ORIGINS= ""
COOKIE_SECURE=True
COOKIE_SAMESITE="none"


# USERBOT
SESSION_STRING = ""
SOURCE_CHANNEL_IDS = []

# MISC
CHANNEL_ID = -1000000000
DUMP_CHANNEL_ID = 0

# LYRICS API
LRCLIB = False
MUSIXMATCH = True

# SPOTIFY
SPOTIFY_CLIENT_ID = ""
SPOTIFY_CLIENT_SECRET = ""

# MULTI-CLIENTS
MULTI_CLIENTS = False
MULTI_CLIENTS_1 = ""
MULTI_CLIENTS_2 = ""
MULTI_CLIENTS_3 = ""
MULTI_CLIENTS_4 = ""
